# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3c18871a3beb8b71165964ccf3bb5f1fdf4ce06da15bc21b1c040d42fa6ed4565a3e181129589b937d31a5861a8c9b05ad95831182cd6a5e779b3dc145dc912

test:
  secret_key_base: 90761b520d1f348189d3c62b2af6fe4fb664b6bc7a46cf035d7861d5e311371b36dfcf9f660948c3f933d7f232e2d22f5576fe0808f6d893940b7e8c07865292

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
